### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by jeremywight** [adrienjoly/chrome-inbox-permalinks#11]
Is this project now abandoned? It doesn't seem to function as expected and it seems like it's been a long time since anyone worked on this repo.

**Comment by adrienjoly** [comment]
Hi Jeremy, thanks for asking!

Google inbox does not exist anymore. So, yeah, this extension has become
useless as a result 😅

-- 
Envoyé avec Gmail Mobile

**Comment by jeremywight** [comment]
@adrienjoly ahh! I missed that it was for Google "Inbox" I forgot that they had had that separate product. Bummer as this would be a really helpful function for Gmail and it seems that nothing will actually support perma-links for Gmail. Thanks for building it none-the-less!

**Comment by adrienjoly** [comment]
To me, permalinks are already provided by gmail out of the box: when you
click on an email conversation, your address bar shows the URL of that
conversation. This was not the case in google inbox: the URL was always the
same, whatever what conversation you had clicked on. That’s why I had
developed this extension for it.

I’d be curious to know what do you mean by « permalinks » in the context of
gmail. Or an example scenario showing how you would use these permalinks.

Adrien
-- 
Envoyé avec Gmail Mobile
